openapi: 3.1.0
info:
  title: Example API
  version: 1.0.0
  license:
    name: UNLICENSED
    url: 'https://example.com/tos'
servers:
  - url: https://api.example.com
    description: Main API server
paths:
  /api/v1/islands/cms/posts:
    get:
      tags:
        - Examples
      operationId: GetPosts
      summary: Get all posts
      security: []
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                $ref: '../types/json-schema/islands/GetIslandPostsResponse.json'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../types/json-schema/shared/BadRequestError.json'
                  - $ref: '../types/json-schema/shared/AppError.json'
