#!/bin/bash
set -euo pipefail

source scripts/helpers.sh

print_header "  📦  Beginning distribution script"
echo ""
echo "  This step puts a subset of our generated output in a dist/ directory"
echo "  which is intended to be consumed by other applications."
echo ""
echo ""

print_header "  🔗 ⏳ Bundling our json2ts typescript types into a single file"
echo ""
echo "  json2ts outputs all of our models into their own files. This step puts"
echo "  all these types into a single file, which makes it easier to use."
echo ""

mkdir -p dist/typescript

header='/**
 * This file is auto-generated.
 *
 * It contains TypeScript types generated from JSON schemas.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
'
{
  echo "$header"
  find generated/typescript/json2ts -type f | while read -r file; do
    echo -e "\n\n// source file: $file"
    cat "$file"
  done
} > dist/typescript/types.d.ts

echo ""
print_header "  🔗  ✅ Done!"

echo ""
echo ""

print_header "  📦 sticking our openapi files in dist/"

mkdir -p dist/openapi
cp -r generated/openapi dist/

echo ""
echo ""

print_header "  📦  ✅ Done!"
